global:
  scrape_interval: 15s  # Her 15 saniyede bir metrikleri al

scrape_configs:
  - job_name: 'mcp-service-control'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']